using AutoGenerated;
using UnityEngine;
using UsefulToolkit.Framework.External;

namespace Sandbox.External
{
    /// <summary>
    /// シーン遷移テスト用のSceneFlowAsset。
    /// SceneFlowAsset&lt;T&gt;はジェネリックなのでそのままではアセット化できないため、
    /// BuildScenesを型引数に固定した非ジェネリックな派生をここで用意する。
    /// enumが出てくるのはこのアセットの中だけで、実行時はシーン名の文字列で扱われる。
    ///
    /// 中身(ノード・シーングループ・遷移)はSceneFlowGraphウィンドウかインスペクタで組むこと。
    /// </summary>
    [CreateAssetMenu(fileName = "SandboxSceneFlow", menuName = "Sandbox/Scene Flow", order = 0)]
    public sealed class SandboxSceneFlowAsset : SceneFlowAsset<BuildScenes>
    {
    }
}
