using UnityEngine;
using UsefulToolkit.External.Scene;

namespace Sandbox.External
{
    /// <summary>
    /// SceneGroup のシーン参照自己修復をテストするための具象アセット型。
    /// </summary>
    [CreateAssetMenu(menuName = "Sandbox/Scene Group Data", fileName = "SandboxSceneGroupData")]
    public sealed class SandboxSceneGroupData : SceneGroupDataBase<AutoGenerated.BuildScenes>
    {
    }
}
