// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum BuildScenes
    {
        UsefulToolkitPersistent = 0,
        Persistent = 1,
        TitleScene = 2,
        InGameScene = 3,
        Stage1 = 4,
        Stage2 = 5,
        Tutorial = 6,
        Lighathing = 7
    }
}
