// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum BuildScenes
    {
        Persistent,
        TitleScene,
        InGameScene,
        Stage1,
        Stage2,
        Tutorial,
        Lighathing
    }
}
