// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum BuildScenes
    {
        Persistent = 0,
        TitleScene = 1,
        InGameScene = 2,
        Stage1 = 3,
        Stage2 = 4,
        Tutorial = 5,
        Lighathing = 6
    }
}
