// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Controls;
using UnityEngine.InputSystem.Layouts;

namespace AutoGenerated
{
    /// <summary>
    /// 外部入力を受ける仮想デバイス。
    /// InputActionAsset からは &lt;UsefulInput&gt;/スロット名 でバインドする。
    /// </summary>
    [InputControlLayout(stateType = typeof(UsefulInputState), displayName = "Useful Input")]
    public sealed class UsefulInputDevice : InputDevice
    {
        public Vector2Control MoveStick { get; private set; }
        public ButtonControl Attack { get; private set; }

        protected override void FinishSetup()
        {
            base.FinishSetup();

            MoveStick = GetChildControl<Vector2Control>("MoveStick");
            Attack = GetChildControl<ButtonControl>("Attack");
        }
    }
}
