// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。

using UnityEngine;
using UnityEngine.InputSystem;

namespace AutoGenerated
{
    /// <summary>
    /// UsefulInputDevice のレイアウト登録とデバイス生成。
    /// 利用者が呼ぶ必要はない。
    /// </summary>
#if UNITY_EDITOR
    [UnityEditor.InitializeOnLoad]
#endif
    public static class UsefulInputDeviceRegistration
    {
#if UNITY_EDITOR
        static UsefulInputDeviceRegistration()
        {
            Register();
        }
#endif

        /// <summary>
        /// レイアウトを登録し、デバイスが未生成なら生成する。
        /// InputActionAssetがバインディングを解決するより前に通す必要がある。
        /// </summary>
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        private static void Register()
        {
            InputSystem.RegisterLayout<UsefulInputDevice>("UsefulInput");

            if (InputSystem.GetDevice<UsefulInputDevice>() != null) return;

            InputSystem.AddDevice<UsefulInputDevice>();
        }
    }
}
