// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。

using System;
using Unity.Collections.LowLevel.Unsafe;
using UnityEngine;
using UnityEngine.InputSystem;
using UsefulToolkit.BlackBoard.Input;

namespace AutoGenerated
{
    /// <summary>
    /// 外部入力を UsefulInputDevice へ書き込む橋渡し。
    /// 生成された InputInitializer が生成して InputManager へ渡す。
    /// </summary>
    public sealed class UsefulInputDeviceBridge : IExternalInputDeviceBridge
    {
        public bool TryWrite<TValue>(Enum slot, TValue value) where TValue : unmanaged
        {
            if (slot is not ExternalInputs target)
            {
                Debug.LogError($"[UsefulToolkit.Input] [{slot}] は ExternalInputs ではない為、書き込めません。");
                return false;
            }

            var device = InputSystem.GetDevice<UsefulInputDevice>();

            if (device == null)
            {
                Debug.LogError("[UsefulToolkit.Input] UsefulInputDevice が生成されていない為、書き込めません。");
                return false;
            }

            switch (target)
            {
                case ExternalInputs.MoveStick:
                    if (typeof(TValue) != typeof(Vector2))
                        return TypeMismatch(target, typeof(Vector2), typeof(TValue));
                    InputSystem.QueueDeltaStateEvent(device.MoveStick, UnsafeUtility.As<TValue, Vector2>(ref value));
                    return true;

                case ExternalInputs.Attack:
                    if (typeof(TValue) != typeof(bool))
                        return TypeMismatch(target, typeof(bool), typeof(TValue));
                    InputSystem.QueueDeltaStateEvent(device.Attack, UnsafeUtility.As<TValue, bool>(ref value) ? 1f : 0f);
                    return true;

                default:
                    Debug.LogError($"[UsefulToolkit.Input] スロット [{target}] は生成されていません。");
                    return false;
            }
        }

        /// <summary>
        /// 宣言された型と書き込もうとした型が食い違う旨をエラーログに出す。
        /// </summary>
        private static bool TypeMismatch(ExternalInputs slot, Type expected, Type actual)
        {
            Debug.LogError($"[UsefulToolkit.Input] スロット [{slot}] は {expected.Name} 型として宣言されている為、{actual.Name} 型では書き込めません。");
            return false;
        }
    }
}
