using System;
using UnityEditor;

namespace UsefulToolkit.Framework
{
    [FilePath("ProjectSettings/UsefulToolkitSettings.asset", FilePathAttribute.Location.ProjectFolder)]
    public class UsefulToolkitSettingsScriptable : ScriptableSingleton<UsefulToolkitSettingsScriptable>
    {
        public PackageSectionSettings PackageSectionSettings = new();
        public CodeGenerationSectionSettings CodeGenerationSectionSettings = new();
        public MaintenanceSectionSettings MaintenanceSectionSettings = new();
        public AboutSectionSettings AboutSectionSettings = new();

        public void Save()
        {
            Save(true);
        }
    }

    /// <summary>
    /// パッケージ管理をするための設定情報を保持するクラス
    /// 機能別のインストール、アンインストールを実行できる
    /// </summary>
    [Serializable]
    public class PackageSectionSettings
    {
    }

    /// <summary>
    /// コード自動生成に関する設定情報を保持するクラス
    /// 自動生成コードの生成場所、タイミングを保持する等
    /// </summary>
    [Serializable]
    public class CodeGenerationSectionSettings
    {
        public string RuntimeSavePath = "Assets/Code/AutoGenerated";
        public string LocalSavePath = "Assets/LocalAssets/AutoGenerated/Editor";
        public string Namespace = "AutoGenerated";
        public GenerateTiming Timing = GenerateTiming.OnAssetChanged;
    }

    /// <summary>
    /// 各種プロジェクトセッティング設定初期化
    /// </summary>
    [Serializable]
    public class MaintenanceSectionSettings
    {
    }

    /// <summary>
    /// バージョン管理を行う
    /// </summary>
    [Serializable]
    public class AboutSectionSettings
    {
        public string Version = "1.0.0";
    }
}