// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : CompositerTestScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>CompositerTestScene の合成ルート。</summary>
    public sealed class CompositerTestSceneCompositer : UsefulToolkit.Initialization.GameCompositer
    {
        [SerializeField] private System.Collections.Generic.List<Sandbox.Initialization.CompositerTestMultiple> _compositerTestMultipleList = new();
        [SerializeField] private Sandbox.Initialization.GameManagementInitializer _gameManagementInitializer;
        [SerializeField] private Sandbox.Initialization.PauseInitializer _pauseInitializer;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new Sandbox.BlackBoard.CompositerTestStateBoard());
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.ProgramTools.PauseBoard());
            blackBoard.TryRegisterEventBoard(new Sandbox.BlackBoard.CompositerTestEventBoard());
            blackBoard.TryRegisterEventBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
        }

        protected override void InjectAll()
        {
            if (_gameManagementInitializer != null)
            {
                {
                    if (TryGetContent<Sandbox.Application.IPauseManager>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<Sandbox.Application.IPauseManager>)_gameManagementInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : GameManagementInitializer (IPauseManager)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            foreach (var target in _compositerTestMultipleList)
            {
                if (target != null) target.Initialize(blackBoard);
            }
            if (_gameManagementInitializer != null) _gameManagementInitializer.Initialize(blackBoard);
            if (_pauseInitializer != null) _pauseInitializer.Initialize(blackBoard);
        }
    }
}
