// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : CompositerTestScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>CompositerTestScene の合成ルート。</summary>
    public sealed class CompositerTestSceneCompositer : UsefulToolkit.Architecture.GameCompositer
    {
        [SerializeField] private Sandbox.Initialization.CompositerTestConsumer _compositerTestConsumer;
        [SerializeField] private System.Collections.Generic.List<Sandbox.Initialization.CompositerTestMultiple> _compositerTestMultipleList = new();
        [SerializeField] private Sandbox.Initialization.CompositerTestProvider _compositerTestProvider;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new Sandbox.BlackBoard.CompositerTestStateBoard());
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.ProgramTools.PauseBoard());
            blackBoard.TryRegisterEventBoard(new Sandbox.BlackBoard.CompositerTestEventBoard());
            blackBoard.TryRegisterEventBoard(new UsefulToolkit.Input.InputBoard());
        }

        protected override void InjectAll()
        {
            if (_compositerTestConsumer != null)
            {
                {
                    if (TryGetContent<UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard>(out var dep0) && TryGetContent<Sandbox.Initialization.CompositerTestProvider>(out var dep1))
                    {
                        ((UsefulToolkit.Architecture.IInjectable<UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard, Sandbox.Initialization.CompositerTestProvider>)_compositerTestConsumer).Inject(dep0, dep1);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : CompositerTestConsumer (IBlackBoard, CompositerTestProvider)", this);
                    }
                }
            }

        }

        protected override void InitializeAll()
        {
            if (_compositerTestConsumer != null) _compositerTestConsumer.Initialize();
            foreach (var target in _compositerTestMultipleList)
            {
                if (target != null) target.Initialize();
            }
            if (_compositerTestProvider != null) _compositerTestProvider.Initialize();
        }
    }
}
