// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : ExternalInputTest

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>ExternalInputTest の合成ルート。</summary>
    public sealed class ExternalInputTestCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.ExternalInputTestCompositor>
    {
        [SerializeField] private Sandbox.Initialization.ExternalInputTester _externalInputTester;

        protected override void InjectAll()
        {
            if (_externalInputTester != null)
            {
                {
                    if (TryGetContent<UsefulToolkit.BlackBoard.Input.IInputController>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<UsefulToolkit.BlackBoard.Input.IInputController>)_externalInputTester).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : ExternalInputTester (IInputController)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_externalInputTester != null) _externalInputTester.Initialize(blackBoard);
        }
    }
}
