using System;
using System.Collections.Generic;
using AutoGenerated;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.Initialization;

namespace Sandbox.Initialization
{
    /// <summary>
    /// 外部入力(生成された仮想デバイス)の動作を確認するためのテスト用ハーネス。
    ///
    /// 上段 : ExternalTest マップの有効状態と、ReadValue で読んだ現在値。
    /// 中段 : RegisterInput で受け取ったコールバックの回数と最新値。
    /// 下段 : WriteExternalInput による書き込みと、ExternalTest マップの有効・無効の切り替え。
    ///
    /// InputActionAsset の ExternalTest マップは、Move が &lt;UsefulInput&gt;/MoveStick、
    /// Attack が &lt;UsefulInput&gt;/Attack にバインドされている前提。
    ///
    /// ExternalInputTest シーンの Compositor に配線して使う。テスト専用。
    /// </summary>
    public sealed class ExternalInputTester : InitializerBase, IInjectable<IInputController>
    {
        [SerializeField]
        [Tooltip("OnGUI の表示位置。他のテスト用ハーネスと重ならないようにする。")]
        private Vector2 _guiPosition = new Vector2(350f, 10f);

        private IInputState _inputState;
        private IInputController _inputController;

        private readonly List<IDisposable> _registrations = new();

        private int _moveCallbackCount;
        private int _attackCallbackCount;
        private string _lastMoveLog = "なし";
        private string _lastAttackLog = "なし";

        /// <summary>
        /// 操作面をDIコンテナから受け取る。常駐シーンの InputInitializer が登録したもの。
        /// </summary>
        /// <param name="inputController">入力の操作面</param>
        public void Inject(IInputController inputController)
        {
            _inputController = inputController;
        }

        /// <summary>
        /// IInputState を取得してコールバックを登録し、ExternalTest マップを追加で有効にする。
        /// </summary>
        /// <param name="blackBoard">IInputState の取得元</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            if (_inputController == null)
            {
                Debug.LogError("[ExternalInputTester] IInputControllerが注入されていません。", this);
                return;
            }

            if (!blackBoard.TryGetStateBoard<InputBoard>(out var inputBoard) ||
                !inputBoard.TryGetGameState<IInputState>(out _inputState))
            {
                Debug.LogError("[ExternalInputTester] IInputStateを取得できません。", this);
                return;
            }

            _registrations.Add(_inputState.RegisterInput<Vector2>(
                ActionMaps.ExternalTest, ExternalTestActions.Move, OnMove));

            _registrations.Add(_inputState.RegisterInput<float>(
                ActionMaps.ExternalTest, ExternalTestActions.Attack, OnAttack));

            _inputController.EnableActionMap(ActionMaps.ExternalTest);

            base.Initialize(blackBoard);
        }

        private void OnDestroy()
        {
            foreach (var registration in _registrations)
            {
                registration.Dispose();
            }

            _registrations.Clear();
        }

        private void OnMove(InputContext<Vector2> context)
        {
            _moveCallbackCount++;
            _lastMoveLog = $"{context.Phase} / {context.Value}";
        }

        private void OnAttack(InputContext<float> context)
        {
            _attackCallbackCount++;
            _lastAttackLog = $"{context.Phase} / {context.Value:0.00}";
        }

        private void OnGUI()
        {
            if (!Initialized) return;

            var area = new Rect(_guiPosition.x, _guiPosition.y, 340f, 330f);

            using (new GUILayout.AreaScope(area, GUIContent.none, GUI.skin.box))
            {
                GUILayout.Label("ExternalInputTester");

                var move = _inputState.ReadValue<Vector2>(ActionMaps.ExternalTest, ExternalTestActions.Move);
                var attack = _inputState.ReadValue<float>(ActionMaps.ExternalTest, ExternalTestActions.Attack);

                GUILayout.Label($"ExternalTest有効 : {_inputState.IsActionMapActive(ActionMaps.ExternalTest)}");
                GUILayout.Label($"ReadValue(Move) : {move.Phase} / {move.Value}");
                GUILayout.Label($"ReadValue(Attack) : {attack.Phase} / {attack.Value:0.00}");

                GUILayout.Space(4f);
                GUILayout.Label($"Move : {_moveCallbackCount}回 / 最新 {_lastMoveLog}");
                GUILayout.Label($"Attack : {_attackCallbackCount}回 / 最新 {_lastAttackLog}");

                GUILayout.Space(4f);

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Move (1,0)"))
                        _inputController.WriteExternalInput(ExternalInputs.MoveStick, new Vector2(1f, 0f));
                    if (GUILayout.Button("Move (0,1)"))
                        _inputController.WriteExternalInput(ExternalInputs.MoveStick, new Vector2(0f, 1f));
                    if (GUILayout.Button("Move (0,0)"))
                        _inputController.WriteExternalInput(ExternalInputs.MoveStick, Vector2.zero);
                }

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Attack 押す")) _inputController.WriteExternalInput(ExternalInputs.Attack, true);
                    if (GUILayout.Button("Attack 離す")) _inputController.WriteExternalInput(ExternalInputs.Attack, false);
                }

                if (GUILayout.Button("型違いの書き込み (MoveStick へ float) → エラーログが出れば正常"))
                {
                    _inputController.WriteExternalInput(ExternalInputs.MoveStick, 1f);
                }

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("ExternalTest 有効")) _inputController.EnableActionMap(ActionMaps.ExternalTest);
                    if (GUILayout.Button("ExternalTest 無効")) _inputController.DisableActionMap(ActionMaps.ExternalTest);
                }
            }
        }
    }
}
