// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : InGameScene

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>InGameScene の合成ルート。</summary>
    public sealed class InGameSceneCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.InGameSceneCompositor>
    {
        [SerializeField] private Sandbox.Initialization.PauseButtonInitializer _pauseButtonInitializer;

        protected override void InjectAll()
        {
            if (_pauseButtonInitializer != null)
            {
                {
                    if (TryGetContent<Sandbox.Application.IPauseManager>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<Sandbox.Application.IPauseManager>)_pauseButtonInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : PauseButtonInitializer (IPauseManager)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_pauseButtonInitializer != null) _pauseButtonInitializer.Initialize(blackBoard);
        }
    }
}
