// UsefulToolkit が生成した Initializer のテンプレートです。
// 中身は自由に書き換えられます。再生成時、このファイルが既に存在する場合は上書きされません。
// 生成元シーン : UsefulToolkitPersistent

using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.Initialization;

namespace AutoGenerated
{
    /// <summary>入力システムの初期化と、(map, action) の橋渡しを行う。</summary>
    public sealed class InputInitializer : InputInitializerBase
    {
        private void Awake()
        {
            // 入力の操作面をDIコンテナへ登録する。BlackBoardには載せない。
            // 受け取る側は IInjectable<UsefulToolkit.BlackBoard.Input.IInputController> を実装する。
            UsefulToolkitPersistentCompositor.TryRegisterContent(Controller);
        }

        /// <param name="blackBoard">InputStateの登録先</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            // ここに (map, action) の Bind と、有効にする ActionMap の指定を書く。
            // Bind は InputActionAsset の Action を入力ソースとしてチャンネルへ繋ぐ操作で、
            // UsefulToolkit/Input/Generate Action Enums が生成した enum を使う。
            //
            // 例:
            // Controller.Bind<UnityEngine.Vector2>(ActionMaps.Player, PlayerActions.Move);
            // Controller.SwitchActionMap(ActionMaps.Player);
        }
    }
}
