using System;
using System.Collections.Generic;
using AutoGenerated;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.Initialization;

namespace Sandbox.Initialization
{
    /// <summary>
    /// Stateベースへ移行した入力管理を実機で確認するためのテスト用ハーネス。
    ///
    /// 上段 : <see cref="IInputState"/> の読み取り面(InputEnabled / ActiveActionMaps / ReadValue)。
    /// 中段 : コールバックの発火状況と、変更通知の受信状況。
    /// 下段 : <see cref="IInputController"/> の操作面(ActionMap切り替え・入力の有効無効)と、
    ///        入力ソースが繋がらないActionに対する RegisterInputAsync のタイムアウト確認。
    ///
    /// 読み取り面はBlackBoardから、操作面はDIコンテナから受け取る。
    /// 操作面をBlackBoard越しに取得する経路は存在しない。
    ///
    /// UsefulToolkitPersistentシーンのGameCompositorに配線して使う。テスト専用。
    /// </summary>
    public sealed class InputStateTester : InitializerBase, IInjectable<IInputController>
    {
        [SerializeField]
        [Tooltip("OnGUI の表示位置。他のテスト用ハーネスと重ならないようにする。")]
        private Vector2 _guiPosition = new Vector2(10f, 450f);

        private IInputState _inputState;
        private IInputController _inputController;

        private readonly List<IDisposable> _registrations = new();

        private int _moveCallbackCount;
        private int _attackCallbackCount;
        private string _lastMoveLog = "なし";
        private string _lastAttackLog = "なし";
        private string _inputEnabledChangedLog = "なし";
        private string _actionMapsChangedLog = "なし";
        private string _asyncRegisterLog = "未実行";

        /// <summary>
        /// 操作面をDIコンテナから受け取る。生成されたInputInitializerがAwakeで登録したもの。
        /// </summary>
        /// <param name="inputController">入力の操作面</param>
        public void Inject(IInputController inputController)
        {
            _inputController = inputController;
        }

        /// <summary>
        /// IInputStateを取得し、変更通知の購読・入力ソースの橋渡し・コールバック登録を行う。
        ///
        /// InputStateの登録もBindもInputInitializerのInitializeより後である必要がある。
        /// InputInitializerBaseはInitializeOrderConst.InitializerEarlyを宣言しており、
        /// このクラスは未宣言(0)なので生成されるInitializeAllでは必ず後になる。
        /// </summary>
        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            if (_inputController == null)
            {
                Debug.LogError("[InputStateTester] IInputControllerが注入されていません。", this);
                return;
            }

            if (!blackBoard.TryGetStateBoard<InputBoard>(out var inputBoard))
            {
                Debug.LogError("[InputStateTester] InputBoardがBlackBoardに登録されていません。", this);
                return;
            }

            if (!inputBoard.TryGetGameState<IInputState>(out _inputState))
            {
                Debug.LogError("[InputStateTester] IInputStateが登録されていません。", this);
                return;
            }

            _registrations.Add(_inputState.RegisterEventOnInputEnabledChanged(
                new ActionEntry<StateContext<bool>>(false, OnInputEnabledChanged)));

            _registrations.Add(_inputState.RegisterEventOnActiveActionMapsChanged(
                new ActionEntry(false, OnActiveActionMapsChanged)));

            _inputController.Bind<Vector2>(ActionMaps.Player, PlayerActions.Move);
            _inputController.Bind<float>(ActionMaps.Player, PlayerActions.Attack);

            _registrations.Add(_inputState.RegisterInput<Vector2>(
                ActionMaps.Player, PlayerActions.Move, OnMove));

            _registrations.Add(_inputState.RegisterInput<float>(
                ActionMaps.Player, PlayerActions.Attack, OnAttack));

            _inputController.SwitchActionMap(ActionMaps.Player);
        }

        private void OnDestroy()
        {
            foreach (var registration in _registrations)
            {
                registration.Dispose();
            }

            _registrations.Clear();
        }

        private void OnMove(InputContext<Vector2> context)
        {
            _moveCallbackCount++;
            _lastMoveLog = $"{context.Phase} / {context.Value}";
        }

        private void OnAttack(InputContext<float> context)
        {
            _attackCallbackCount++;
            _lastAttackLog = $"{context.Phase} / {context.Value:0.00}";
        }

        private void OnInputEnabledChanged(StateContext<bool> context)
        {
            _inputEnabledChangedLog = $"{context.OldValue} -> {context.NewValue}";
        }

        private void OnActiveActionMapsChanged()
        {
            _actionMapsChangedLog = FormatActiveActionMaps();
        }

        /// <summary>
        /// 入力ソースが繋がらないActionへRegisterInputAsyncを掛け、タイムアウトまでの経過秒数を記録する。
        /// </summary>
        private async UniTaskVoid TestRegisterInputAsync()
        {
            _asyncRegisterLog = "待機中...";

            float startTime = Time.realtimeSinceStartup;

            var registration = await _inputState.RegisterInputAsync<float>(
                ActionMaps.UI, UIActions.Submit, OnAttack, 2f);

            _asyncRegisterLog = $"{Time.realtimeSinceStartup - startTime:0.00}秒で終了";
            _registrations.Add(registration);
        }

        private string FormatActiveActionMaps()
        {
            if (_inputState == null || _inputState.ActiveActionMaps.Count == 0) return "なし";

            return string.Join(", ", _inputState.ActiveActionMaps);
        }

        private void OnGUI()
        {
            if (!Initialized) return;

            var area = new Rect(_guiPosition.x, _guiPosition.y, 330f, 330f);

            using (new GUILayout.AreaScope(area, GUIContent.none, GUI.skin.box))
            {
                GUILayout.Label("InputStateTester");

                if (_inputState == null)
                {
                    GUILayout.Label("IInputState : 未取得");
                    return;
                }

                var move = _inputState.ReadValue<Vector2>(ActionMaps.Player, PlayerActions.Move);

                GUILayout.Label($"InputEnabled : {_inputState.InputEnabled}");
                GUILayout.Label($"ActiveActionMaps : {FormatActiveActionMaps()}");
                GUILayout.Label($"Player有効 : {_inputState.IsActionMapActive(ActionMaps.Player)} / " +
                                $"UI有効 : {_inputState.IsActionMapActive(ActionMaps.UI)}");
                GUILayout.Label($"ReadValue(Move) : {move.Phase} / {move.Value}");

                GUILayout.Space(4f);
                GUILayout.Label($"Move : {_moveCallbackCount}回 / 最新 {_lastMoveLog}");
                GUILayout.Label($"Attack : {_attackCallbackCount}回 / 最新 {_lastAttackLog}");
                GUILayout.Label($"InputEnabled変更通知 : {_inputEnabledChangedLog}");
                GUILayout.Label($"ActionMaps変更通知 : {_actionMapsChangedLog}");

                GUILayout.Space(4f);

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Switch Player")) _inputController.SwitchActionMap(ActionMaps.Player);
                    if (GUILayout.Button("Switch UI")) _inputController.SwitchActionMap(ActionMaps.UI);
                }

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Enable UI")) _inputController.EnableActionMap(ActionMaps.UI);
                    if (GUILayout.Button("Disable UI")) _inputController.DisableActionMap(ActionMaps.UI);
                }

                using (new GUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Enable Input")) _inputController.EnableInput();
                    if (GUILayout.Button("Disable Input")) _inputController.DisableInput();
                }

                GUILayout.Label($"RegisterInputAsync : {_asyncRegisterLog}");

                if (GUILayout.Button("Async登録テスト (UI.Submit / 2秒)"))
                {
                    TestRegisterInputAsync().Forget();
                }
            }
        }
    }
}
