using AutoGenerated;
using Sandbox.Application;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.Initialization;

namespace Sandbox.Initialization
{
    /// <summary>
    /// 常駐シーンに置く供給側の Initializer。PauseManager を生成して Root スコープへ登録し、
    /// Initialize で State を作らせる。
    ///
    /// Awake で生成と登録、Initialize で State 生成という 2 段構えなのは、
    /// TryRegisterContent が Collection フェーズ限定である一方、
    /// BlackBoard が渡るのは Initialize フェーズだから。
    /// </summary>
    public sealed class PauseInitializer : InitializerBase
    {
        private PauseManager _pauseManager;

        private void Awake()
        {
            _pauseManager = new PauseManager();

            // 常駐シーンの Compositor へ登録する為、他のシーンからも Root スコープ経由で解決できる。
            UsefulToolkitPersistentCompositor.TryRegisterContent<IPauseManager>(_pauseManager);
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            _pauseManager.Initialize(blackBoard);
        }
    }
}
