using System;
using System.Collections.Generic;
using System.Text;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.SceneManagement;
using UsefulToolkit.Initialization;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Scene;
using UsefulToolkit.Application.Scene;
using UsefulToolkit.External.Scene;
using AutoGenerated;

namespace Sandbox.Initialization
{
    /// <summary>
    /// Phase1で入れたシーンロードの変更点を実機で確認するためのテスト用ハーネス。
    ///
    /// 左カラム : <see cref="ISceneState"/> を直接叩くシナリオ(旧アクティブの降格・常駐保護・上書きロード)。
    /// 右カラム : <see cref="SceneLoadService"/> 経由のシーングループ操作と、
    ///           常駐シーン起動から開始グループへ遷移する <see cref="SceneLoadService.Initialize"/>。
    ///
    /// 各シーンに付いているSceneMarkerと合わせて挙動を目視する。
    /// UsefulToolkitPersistentシーンのGameCompositerに配線して使う。テスト専用。
    /// </summary>
    public sealed class SceneTransitionTester : InitializerBase
    {
        private ISceneState _sceneState;
        private SceneLoadService _sceneLoadService;

        // ボタン連打で要求が重なるのを避けるための簡易ロック
        private bool _busy;

        // テスト用のシーングループ。実際の利用では SceneGroupData アセットから来る。
        private static readonly (string label, SceneGroup group)[] TestGroups =
        {
            ("0: OutGame (main=Title)",
                new SceneGroup(true, new[] { (int)BuildScenes.TitleScene })),
            ("1: InGame (main=InGame, +Stage1)",
                new SceneGroup(true, new[] { (int)BuildScenes.InGameScene, (int)BuildScenes.Stage1 })),
            ("2: InGame2 (main=InGame, +Stage2)",
                new SceneGroup(true, new[] { (int)BuildScenes.InGameScene, (int)BuildScenes.Stage2 })),
            ("3: 追加チャンク (main無し, Tutorial)",
                new SceneGroup(false, new[] { (int)BuildScenes.Tutorial })),
        };

        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            if (blackBoard.GetSceneBoard().TryGetGameState<ISceneState>(out _sceneState))
            {
                Debug.Log("[Tester] ISceneState を取得しました。");
            }
            else
            {
                Debug.LogError("[Tester] ISceneState を取得できませんでした。");
            }

            var groups = new SceneGroup[TestGroups.Length];
            for (int i = 0; i < TestGroups.Length; i++)
            {
                groups[i] = TestGroups[i].group;
            }

            _sceneLoadService = new SceneLoadService(blackBoard, groups);
            Debug.Log($"[Tester] SceneLoadService を生成しました。GroupCount={_sceneLoadService.GroupCount}");
        }

        private void OnGUI()
        {
            if (_sceneState == null)
            {
                GUILayout.BeginArea(new Rect(10f, 10f, 460f, 60f), GUI.skin.box);
                GUILayout.Label("ISceneState 未取得");
                GUILayout.EndArea();
                return;
            }

            DrawSceneStateColumn();
            DrawSceneLoadServiceColumn();
        }

        private void DrawSceneStateColumn()
        {
            GUILayout.BeginArea(new Rect(10f, 10f, 470f, 620f), GUI.skin.box);

            GUILayout.Label("=== ISceneState 直接 ===");
            GUILayout.Label(DescribeState());
            GUILayout.Space(6f);

            GUI.enabled = !_busy;

            if (GUILayout.Button("A. 追加ロード: Title (初回なのでアクティブになる)"))
            {
                Run("A RequestLoad(Title, [])",
                    () => _sceneState.RequestLoadAsync(Id(BuildScenes.TitleScene), Array.Empty<int>()));
            }

            if (GUILayout.Button("B. メイン差し替え: InGame + Stage1 (旧TitleはAdditiveへ降格)"))
            {
                Run("B RequestLoad(InGame, [Stage1])",
                    () => _sceneState.RequestLoadAsync(Id(BuildScenes.InGameScene), Ids(BuildScenes.Stage1)));
            }

            if (GUILayout.Button("C. 差分ロード: InGame + Stage2 (Stage1は再ロードされない)"))
            {
                Run("C RequestLoad(InGame, [Stage2])",
                    () => _sceneState.RequestLoadAsync(Id(BuildScenes.InGameScene), Ids(BuildScenes.Stage2)));
            }

            if (GUILayout.Button("D. 上書きロード: InGame + Tutorial (Title/Stage1/Stage2はアンロード)"))
            {
                Run("D RequestOverwriteLoad(InGame, [Tutorial])",
                    () => _sceneState.RequestOverwriteLoadAsync(Id(BuildScenes.InGameScene), Ids(BuildScenes.Tutorial)));
            }

            if (GUILayout.Button("E. 追加グループ(メイン無し): +Stage1 +Stage2 (アクティブは不変)"))
            {
                Run("E RequestLoad(NoScene, [Stage1, Stage2])",
                    () => _sceneState.RequestLoadAsync(SceneState.NoSceneId, Ids(BuildScenes.Stage1, BuildScenes.Stage2)));
            }

            if (GUILayout.Button("F. 上書き(メイン無し): =Stage1+Stage2のみ (アクティブはNoneへ)"))
            {
                Run("F RequestOverwriteLoad(NoScene, [Stage1, Stage2])",
                    () => _sceneState.RequestOverwriteLoadAsync(SceneState.NoSceneId, Ids(BuildScenes.Stage1, BuildScenes.Stage2)));
            }

            if (GUILayout.Button("G. アンロード: Stage1"))
            {
                Run("G RequestUnLoad([Stage1])",
                    () => _sceneState.RequestUnLoadAsync(Ids(BuildScenes.Stage1)));
            }

            GUILayout.Space(6f);
            GUILayout.Label("--- 常駐シーン保護 (どちらもロードを中止し falseを返すはず) ---");

            if (GUILayout.Button("H. 常駐をアンロード試行: UsefulToolkitPersistent"))
            {
                Run("H RequestUnLoad([UsefulToolkitPersistent])",
                    () => _sceneState.RequestUnLoadAsync(Ids(BuildScenes.UsefulToolkitPersistent)));
            }

            if (GUILayout.Button("I. 常駐をアクティブ化試行: UsefulToolkitPersistent (SetActiveSceneは呼ばれない)"))
            {
                Run("I RequestLoad(UsefulToolkitPersistent, [])",
                    () => _sceneState.RequestLoadAsync(Id(BuildScenes.UsefulToolkitPersistent), Array.Empty<int>()));
            }

            if (GUILayout.Button("I2. 常駐をアクティブ化+サブ試行: (a判定によりサブもロードされない)"))
            {
                Run("I2 RequestLoad(UsefulToolkitPersistent, [Stage1])",
                    () => _sceneState.RequestLoadAsync(Id(BuildScenes.UsefulToolkitPersistent), Ids(BuildScenes.Stage1)));
            }

            GUI.enabled = true;
            GUILayout.Space(6f);

            if (GUILayout.Button("状態をログに出力"))
            {
                Debug.Log("[Tester] " + DescribeState());
            }

            GUILayout.EndArea();
        }

        private void DrawSceneLoadServiceColumn()
        {
            GUILayout.BeginArea(new Rect(490f, 10f, 470f, 420f), GUI.skin.box);

            GUILayout.Label("=== SceneLoadService 経由 ===");
            GUILayout.Space(6f);

            GUI.enabled = !_busy;

            GUILayout.Label("Initialize : 常駐シーン起動 → 開始グループへ (1度だけ)");
            for (int i = 0; i < TestGroups.Length; i++)
            {
                var index = i;
                if (GUILayout.Button($"Initialize(startGroupIndex: {index})  [{TestGroups[index].label}]"))
                {
                    Run($"Initialize({index})",
                        () => _sceneLoadService.Initialize(index));
                }
            }

            GUILayout.Space(8f);
            GUILayout.Label("LoadGroup (overwrite=true : 丸ごと上書き)");
            for (int i = 0; i < TestGroups.Length; i++)
            {
                var index = i;
                if (GUILayout.Button($"LoadGroup({index}, overwrite)  [{TestGroups[index].label}]"))
                {
                    Run($"LoadGroup({index}, overwrite)",
                        () => _sceneLoadService.LoadGroupAsync(index, overwriteLoadedScenes: true));
                }
            }

            GUILayout.Space(8f);
            GUILayout.Label("LoadGroup (overwrite=false : 追加ロード)");
            for (int i = 0; i < TestGroups.Length; i++)
            {
                var index = i;
                if (GUILayout.Button($"LoadGroup({index}, additive)  [{TestGroups[index].label}]"))
                {
                    Run($"LoadGroup({index}, additive)",
                        () => _sceneLoadService.LoadGroupAsync(index, overwriteLoadedScenes: false));
                }
            }

            GUILayout.Space(8f);
            GUILayout.Label("UnLoadGroup");
            for (int i = 0; i < TestGroups.Length; i++)
            {
                var index = i;
                if (GUILayout.Button($"UnLoadGroup({index})  [{TestGroups[index].label}]"))
                {
                    Run($"UnLoadGroup({index})",
                        () => _sceneLoadService.UnLoadGroupAsync(index));
                }
            }

            GUI.enabled = true;
            GUILayout.EndArea();
        }

        /// <summary>
        /// シーン操作を1つ実行し、前後の状態をログへ出す。
        /// </summary>
        private void Run(string label, Func<UniTask<bool>> operation)
        {
            RunAsync(label, operation).Forget();
        }

        private async UniTaskVoid RunAsync(string label, Func<UniTask<bool>> operation)
        {
            if (_busy)
            {
                Debug.LogWarning($"[Tester] 実行中の為スキップ: {label}");
                return;
            }

            _busy = true;
            Debug.Log($"[Tester] ▶ {label}\n  before: {DescribeState()}");

            bool result;
            try
            {
                result = await operation();
            }
            catch (Exception e)
            {
                Debug.LogError($"[Tester] ✕ {label} で例外: {e}");
                _busy = false;
                return;
            }

            Debug.Log($"[Tester] ◀ {label} => {result}\n  after : {DescribeState()}");
            _busy = false;
        }

        private string DescribeState()
        {
            var sb = new StringBuilder();
            sb.Append("Phase=").Append(_sceneState.Phase);
            sb.Append("  Progress=").Append(_sceneState.LoadProgress.ToString("F2"));
            sb.Append('\n');
            sb.Append("Active=").Append(SceneLabel(_sceneState.ActiveScene));
            sb.Append('\n');
            sb.Append("Additive=[");
            var additive = _sceneState.AdditiveScenes;
            for (int i = 0; i < additive.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(SceneLabel(additive[i]));
            }
            sb.Append(']');
            sb.Append('\n');
            sb.Append("Unity.Active=").Append(SceneManager.GetActiveScene().name);
            sb.Append("  loaded=").Append(SceneManager.sceneCount);
            return sb.ToString();
        }

        private static string SceneLabel(int sceneId)
        {
            if (sceneId < 0) return "None";

            var path = SceneUtility.GetScenePathByBuildIndex(sceneId);
            if (string.IsNullOrEmpty(path)) return $"#{sceneId}";

            return $"{System.IO.Path.GetFileNameWithoutExtension(path)}(#{sceneId})";
        }

        private static int Id(BuildScenes scene) => (int)scene;

        private static IReadOnlyList<int> Ids(params BuildScenes[] scenes)
        {
            var ids = new int[scenes.Length];
            for (int i = 0; i < scenes.Length; i++)
            {
                ids[i] = (int)scenes[i];
            }

            return ids;
        }
    }
}
