// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : UsefulToolkitPersistent

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>UsefulToolkitPersistent の合成ルート。</summary>
    public sealed class UsefulToolkitPersistentCompositor : UsefulToolkit.Initialization.RootGameCompositor<AutoGenerated.UsefulToolkitPersistentCompositor>
    {
        [SerializeField] private UsefulToolkit.Initialization.InputInitializer _inputInitializer;
        [SerializeField] private Sandbox.Initialization.InputStateTester _inputStateTester;
        [SerializeField] private Sandbox.Initialization.PauseInitializer _pauseInitializer;
        [SerializeField] private Sandbox.Initialization.SceneTransitionTester _sceneTransitionTester;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.ProgramTools.PauseBoard());
        }

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_inputInitializer != null) _inputInitializer.Initialize(blackBoard); // order: -80
            if (_inputStateTester != null) _inputStateTester.Initialize(blackBoard);
            if (_pauseInitializer != null) _pauseInitializer.Initialize(blackBoard);
            if (_sceneTransitionTester != null) _sceneTransitionTester.Initialize(blackBoard);
        }
    }
}
