// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : UsefulToolkitPersistent

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>UsefulToolkitPersistent の合成ルート。</summary>
    public sealed class UsefulToolkitPersistentCompositer : UsefulToolkit.Initialization.GameCompositer
    {
        [SerializeField] private Sandbox.Initialization.SceneTransitionTester _sceneTransitionTester;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            blackBoard.TryRegisterStateBoard(new Sandbox.BlackBoard.CompositerTestStateBoard());
            blackBoard.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.ProgramTools.PauseBoard());
            blackBoard.TryRegisterEventBoard(new Sandbox.BlackBoard.CompositerTestEventBoard());
            blackBoard.TryRegisterEventBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
        }

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_sceneTransitionTester != null) _sceneTransitionTester.Initialize(blackBoard);
        }
    }
}
