// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum NonBuildScenes
    {
        NetworkingDBTest = 0,
        NetworkingTest = 1,
        CompositerTestScene = 2,
        TestScene = 3,
        SampleScene = 4
    }
}
