// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum NonBuildScenes
    {
        ActionStage_Realistic = -1,
        ShaderTestScene = -2,
        NetworkingDBTest = -3,
        NetworkingTest = -4,
        TestScene = -5,
        SnakeTestScene = -6,
        SampleScene = -7
    }
}
