// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum NonBuildScenes
    {
        NetworkingDBTest = -1,
        NetworkingTest = -2,
        TestScene = -3,
        SampleScene = -4
    }
}
